StarWarsApi/StarWarsApi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using StarWarsApi.Models;
using System.Diagnostics;


namespace StarWarsApi.Controllers
{

    public class HomeController : Controller
    {
        private StarShipContext context { get; set; }

        public HomeController (StarShipContext ctx) => context = ctx;
        
        public IActionResult Index()
        {
            var starships = context.Starships.OrderBy(s => s.name).ToList();
            return View(starships);
        }
    }


    public static class StarshipSeeder
    {

        public static async Task SeedStarShipData(StarShipContext context)
        {
            if (context.Starships.Any())
            {
                return; // Data already seeded
            }

            var httpClient = new HttpClient();
            var response = await httpClient.GetAsync("https://swapi.dev/api/starships/?format=json");
            var apiResponse = await response.Content.ReadAsStringAsync();

            var starshipApiResponse = JsonConvert.DeserializeObject<StarshipApiResponse>(apiResponse);
            var starships = starshipApiResponse.Results;

            context.Starships.AddRange(starships);
            await context.SaveChangesAsync();
        }
    }

}

StarWarsApi/StarWarsApi/Controllers/StarshipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StarWarsApi.Models;

namespace StarWarsApi.Controllers
{
    public class StarshipsController : Controller
    {
        private StarShipContext context { get; set; }

        public StarshipsController(StarShipContext ctx ) => context = ctx;


        [HttpGet]

        // GET: Starships
        public async Task<IActionResult> Index()
        {
            return View(await context.Starships.ToListAsync());
        }


        // GET: Starships/Create
        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            //ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
            return View("Create", new Starship());        
        }

        //POST: Starships/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to.


       [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url")] Starship starship)
        {
            if (ModelState.IsValid)
            {
                context.Add(starship);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(starship);
        }





        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            //ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
            var starship = context.Starships.Find(id);
            return View(starship);
        }

        [HttpPost]
        public IActionResult Edit(Starship starship)
        {
            if (ModelState.IsValid)
            {
                if (starship.Id == 0)
                    context.Starships.Add(starship);
                else
                    context.Starships.Update(starship);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (starship.Id == 0) ? "Create" : "Edit";
                //ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
                return View(starship);
            }
        }



        //// GET: Starships/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var starship = await _context.Starships
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (starship == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(starship);
        //}


        //// GET: Starships/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var starship = await context.Starships.FindAsync(id);
        //    if (starship == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(starship);
        //}

        //// POST: Starships/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url")] Starship starship)
        //{
        //    if (id != starship.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(starship);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!StarshipExists(starship.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(starship);
        //}

        // GET: Starships/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var starship = await context.Starships
                .FirstOrDefaultAsync(m => m.Id == id);
            if (starship == null)
            {
                return NotFound();
            }

            return View(starship);
        }

        // POST: Starships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var starship = await context.Starships.FindAsync(id);
            if (starship != null)
            {
                context.Starships.Remove(starship);
            }

            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StarshipExists(int id)
        {
            return context.Starships.Any(e => e.Id == id);
        }
    }
}

StarWarsApi/StarWarsApi/Views/Home/Index.cshtml
@model List<Starship>

@{
   
}

<div class="mb-2">
    <a asp-controller="Starships" asp-action="Create">Create New Starship</a>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>name</th>
            <th>model</th>
            <th>manufacturer</th>
            <th>cost_in_credits</th>
            <th>length</th>
            <th>max_atmosphering_speed</th>
            <th>crew</th>
            <th>passengers</th>
            <th>cargo_capacity</th>
            <th>consumables</th>
            <th>hyperdrive_rating</th>
            <th>MGLT</th>
            <th>starship_class</th>
@*             <th>pilots</th>
            <th>films</th> *@
        </tr>
    </thead>
    <tbody>
        
        @foreach (var s in Model )
        {
            
       
            <tr>
   
                <td>@s.name</td>
                <td>@s.model</td>
                <td>@s.manufacturer</td>
                <td>@s.cost_in_credits</td>
                <td>@s.length</td>
                <td>@s.max_atmosphering_speed</td>
                <td>@s.crew</td>
                <td>@s.passengers</td>
                <td>@s.cargo_capacity</td>
                <td>@s.consumables</td>
                <td>@s.hyperdrive_rating</td>
                <td>@s.MGLT</td>
                <td>@s.starship_class</td>
@*                 <td>@s.pilots</td>
                   <td>@s.films</td> *@
                <td>
                    <a asp-controller="Starships" asp-action="Edit" asp-route-id="@s.Id" asp-route-slug="@s.slug"> Edit </a>
                <a asp-controller="Starships" asp-action="Delete" asp-route-id="@s.Id" asp-route-slug="@s.slug" > Delete </a>

                </td>

            </tr>
        }
    </tbody>
</table>



    